INSERT INTO BC_service_type(name) VALUES('Accounting');
INSERT INTO BC_service_type(name) VALUES('Advertising (off campus)');
INSERT INTO BC_service_type(name) VALUES('Advertising/Promotional (on campus)');
INSERT INTO BC_service_type(name) VALUES('Agency Funds (journals, Co-op, Union)');
INSERT INTO BC_service_type(name) VALUES('Air Charter');
INSERT INTO BC_service_type(name) VALUES('Arena (ERC) Suite License');
INSERT INTO BC_service_type(name) VALUES('(Longhorn Foundation)');
INSERT INTO BC_service_type(name) VALUES('Armored Car/Security');
INSERT INTO BC_service_type(name) VALUES('Athletic Broadcast Rights');
INSERT INTO BC_service_type(name) VALUES('Athletic Director Employment');
INSERT INTO BC_service_type(name) VALUES('Athletic Games/Events');
INSERT INTO BC_service_type(name) VALUES('Athletic Sponsorships');
INSERT INTO BC_service_type(name) VALUES('Audit Engagement Letters');
INSERT INTO BC_service_type(name) VALUES('Author rights/licenses');
INSERT INTO BC_service_type(name) VALUES('Banking Services');
INSERT INTO BC_service_type(name) VALUES('Beta Tests');
INSERT INTO BC_service_type(name) VALUES('Bevo Bucks Merchant');
INSERT INTO BC_service_type(name) VALUES('Boat Charter');
INSERT INTO BC_service_type(name) VALUES('Building Use (External &Internal)');
INSERT INTO BC_service_type(name) VALUES('Bus Charter');
INSERT INTO BC_service_type(name) VALUES('Camps, Specialty');
INSERT INTO BC_service_type(name) VALUES('Campus Mobile Food/Beverage Cart');
INSERT INTO BC_service_type(name) VALUES('Catering Services (1)');
INSERT INTO BC_service_type(name) VALUES('Charter Schools (Educational Svc)');
INSERT INTO BC_service_type(name) VALUES('Charter Transportation (Air/Boat/Bus)');
INSERT INTO BC_service_type(name) VALUES('Co-location (IT)');
INSERT INTO BC_service_type(name) VALUES('Collection Agency');
INSERT INTO BC_service_type(name) VALUES('Commissioning (Art, Music)');
INSERT INTO BC_service_type(name) VALUES('Concession Services (on-campus)');
INSERT INTO BC_service_type(name) VALUES('Conference Svcs, Ancillary');
INSERT INTO BC_service_type(name) VALUES('Copyright License');
INSERT INTO BC_service_type(name) VALUES('Credit Bureau (skip tracing)');
INSERT INTO BC_service_type(name) VALUES('Custodial & Facilities Maintenance');
INSERT INTO BC_service_type(name) VALUES('Database Licenses');
INSERT INTO BC_service_type(name) VALUES('Educational Service (Army/Air Force)');
INSERT INTO BC_service_type(name) VALUES('Entertainment/Performance');
INSERT INTO BC_service_type(name) VALUES('Equipment Lease');
INSERT INTO BC_service_type(name) VALUES('Equipment Loan');
INSERT INTO BC_service_type(name) VALUES('Exhibit Booth Space (external)');
INSERT INTO BC_service_type(name) VALUES('Exhibition (Museum) Lending');
INSERT INTO BC_service_type(name) VALUES('Executive Program Training & Development');
INSERT INTO BC_service_type(name) VALUES('Facility Use (External & Internal)');
INSERT INTO BC_service_type(name) VALUES('Food Services (operating on-campus)');
INSERT INTO BC_service_type(name) VALUES('Head Coach Employment');
INSERT INTO BC_service_type(name) VALUES('HIPAA Business Associate');
INSERT INTO BC_service_type(name) VALUES('Hotel (function/space/food/auxiliary)');
INSERT INTO BC_service_type(name) VALUES('Housing (off-campus) for conf/camps');
INSERT INTO BC_service_type(name) VALUES('Information Technology Services');
INSERT INTO BC_service_type(name) VALUES('Instructors (Continuing & Innovative Ed.)');
INSERT INTO BC_service_type(name) VALUES('Interlocal Agreement');
INSERT INTO BC_service_type(name) VALUES('Interagency Cooperation Contract (IAC)');
INSERT INTO BC_service_type(name) VALUES('Licenses (for use of copyrighted material)');
INSERT INTO BC_service_type(name) VALUES('Marketing');
INSERT INTO BC_service_type(name) VALUES('Media Advertising (IAM)');
INSERT INTO BC_service_type(name) VALUES('Music Licenses (BMI, ASACP)');
INSERT INTO BC_service_type(name) VALUES('Non-Disclosure (or Confidentiality)');
INSERT INTO BC_service_type(name) VALUES('Performance (Artistic)');
INSERT INTO BC_service_type(name) VALUES('Personal Seat License (ERC, DKR)');
INSERT INTO BC_service_type(name) VALUES('Photograph Permission');
INSERT INTO BC_service_type(name) VALUES('Photography Services');
INSERT INTO BC_service_type(name) VALUES('Programming (Computer, TV, Radio)');
INSERT INTO BC_service_type(name) VALUES('Public Relations');
INSERT INTO BC_service_type(name) VALUES('Publishing');
INSERT INTO BC_service_type(name) VALUES('Radio Program Distribution Agreements');
INSERT INTO BC_service_type(name) VALUES('Recycling');
INSERT INTO BC_service_type(name) VALUES('Settlement');
INSERT INTO BC_service_type(name) VALUES('Software Design/Development');
INSERT INTO BC_service_type(name) VALUES('Speaker Services');
INSERT INTO BC_service_type(name) VALUES('Stadium (DKR, UFCU) Suite Licenses (Longhorn Foundation)');
INSERT INTO BC_service_type(name) VALUES('Storage Facility (off-campus)');
INSERT INTO BC_service_type(name) VALUES('Suite (Single-Use) Licenses (H.S. football)');
INSERT INTO BC_service_type(name) VALUES('Ticket Sales/Ticket Consignment (ERC)');
INSERT INTO BC_service_type(name) VALUES('Training and Development');
INSERT INTO BC_service_type(name) VALUES('Translation services');
INSERT INTO BC_service_type(name) VALUES('Transportation, Shuttle Bus & Others');
INSERT INTO BC_service_type(name) VALUES('Travel Management Services');
INSERT INTO BC_service_type(name) VALUES('University Press Publishing Services');
INSERT INTO BC_service_type(name) VALUES('Utilities (Gas/Transport/Electric)');
INSERT INTO BC_service_type(name) VALUES('Vending Machine');
INSERT INTO BC_service_type(name) VALUES('Visiting Faculty');
INSERT INTO BC_service_type(name) VALUES('Waste');
INSERT INTO BC_service_type(name) VALUES('Management');
INSERT INTO BC_service_type(name) VALUES('Website Design/Hosting');
INSERT INTO BC_service_type(name) VALUES('Work Made for Hire');